import Head from "next/head"
import React from "react"
import type { FC } from "react"
import { Inter } from "next/font/google"
import Main from "@/layouts/Main"
import styled from "styled-components"
import axios from "@/config/axios"
import Link from "next/link"
import { MdOpenInNew } from "react-icons/md"
import { AiFillGithub } from "react-icons/ai"

const inter = Inter({ subsets: ["latin"] })

interface HomeProps {
    props: any
}

export default function Home(props): FC<HomeProps> {
    const { about } = props
    console.log("about", about)

    return (
        <>
            <Head>
                <title>Hieu Thanh | Developer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <IntroSection className="-mt-16">
                    <div className="w-full max-w-2xl px-4 pt-32 pb-40 m-auto text-center text-color-text">
                        <h1 className="text-5xl sm:text-7xl">
                            <span className="font-light">I'm</span>{" "}
                            <span className="font-bold">Hieu Thanh</span>
                        </h1>
                        <h2 className="mt-4 text-lg opacity-90">
                            I'm build things for the{" "}
                            <span className="rounded-full bg-gradient-to-r from-[#6366f1] via-[#a855f7] to-[#ec4899] bg-clip-text font-bold text-transparent">
                                web
                            </span>
                        </h2>
                        <p className="mx-auto mt-8 text-sm opacity-80 sm:text-lg">
                            {about?.data?.attributes?.introduction}
                        </p>
                        <div className="pt-12 flex flex-wrap gap-4 items-center justify-center">
                            <a
                                className="rounded-full bg-color-syntax-fn hover:opacity-75 btn space-x-2 font-semibold"
                                href="mailto:hieuthahn@gmail.com"
                            >
                                <span>👋</span>
                                <span>Contact Me</span>
                            </a>
                            <a
                                className="rounded-full bg-color-blurred-background hover:opacity-75 p btn space-x-2 font-semibold"
                                href="mailto:hieuthahn@gmail.com"
                            >
                                <span>💼</span>
                                <span>My Resume</span>
                            </a>
                        </div>
                    </div>
                    <div className="absolute bottom-0 left-0 w-full">
                        <svg
                            preserveAspectRatio="none"
                            width="1440"
                            height="74"
                            viewBox="0 0 1440 74"
                            className="fill-color-subtle-background w-full"
                            style={{ transition: "fill 350ms ease 0s" }}
                        >
                            <path d="M456.464 0.0433865C277.158 -1.70575 0 50.0141 0 50.0141V74H1440V50.0141C1440 50.0141 1320.4 31.1925 1243.09 27.0276C1099.33 19.2816 1019.08 53.1981 875.138 50.0141C710.527 46.3727 621.108 1.64949 456.464 0.0433865Z"></path>
                        </svg>
                    </div>
                </IntroSection>

                {/* Skills section */}
                <section className="max-w-3xl mx-auto flex flex-col sm:flex-row px-4 py-12 justify-center">
                    <div className="text-color-primary font-bold basis-0 sm:basis-24 text-left sm:text-right mr-20 mb-4">
                        SKILLS
                    </div>
                    <div className="flex-1 grid grid-cols-2 md:grid-cols-4 gap-6 sm:gap-10 justify-center">
                        {Object.entries(about?.data?.attributes?.skills)
                            .reverse()
                            .map(([key, value], index) => {
                                return (
                                    <div key={index} className="">
                                        <div className="font-semibold">
                                            {key.toUpperCase()}
                                        </div>
                                        {value.map((item) => (
                                            <div
                                                key={item}
                                                className="opacity-80"
                                            >
                                                {item}
                                            </div>
                                        ))}
                                    </div>
                                )
                            })}
                    </div>
                </section>

                {/* Experience section */}
                <section className="max-w-3xl mx-auto flex flex-col sm:flex-row px-4 py-12 justify-center">
                    <div className="text-color-primary font-bold basis-0 sm:basis-24 text-left sm:text-right mr-20 mb-4">
                        EXPERIENCE
                    </div>
                    <div className="flex-1">
                        {about?.data?.attributes?.experience.map(
                            (item, index) => {
                                return (
                                    <div
                                        className=" flex-grow flex justify-between"
                                        key={index}
                                    >
                                        <div className="font-semibold">
                                            <Link
                                                href={item?.website || "#"}
                                                target="_blank"
                                                className="block"
                                            >
                                                {item?.company}
                                            </Link>
                                            <span className="font-normal text-sm opacity-80">
                                                {item?.position}
                                            </span>
                                        </div>
                                        <div>{item?.time}</div>
                                    </div>
                                )
                            }
                        )}
                    </div>
                </section>

                {/* Experience section */}
                <section className="max-w-3xl mx-auto flex flex-col sm:flex-row px-4 py-12 justify-center">
                    <div className="text-color-primary font-bold basis-0 sm:basis-24 text-left sm:text-right mr-20 mb-4">
                        PROJECTS
                    </div>
                    <div className="flex-1">
                        {about?.data?.attributes?.projects.map(
                            (item, index) => {
                                return (
                                    <div key={index} className="space-y-2 mb-3">
                                        <div className="font-semibold flex justify-between">
                                            <div>{item?.name}</div>
                                            <div className="flex space-x-2">
                                                <Link
                                                    href={item?.website || "#"}
                                                >
                                                    <MdOpenInNew size={18} />
                                                </Link>
                                                <Link
                                                    href={item?.github || "#"}
                                                >
                                                    <AiFillGithub size={18} />
                                                </Link>
                                            </div>
                                        </div>
                                        <div className="opacity-80">
                                            {item?.description}
                                        </div>
                                        <div className="flex space-x-3">
                                            {item?.technology?.map(
                                                (tech, index) => (
                                                    <span
                                                        className="px-2 py-1 opacity-70 text-sm font-normal bg-gray-500/30 rounded-md font-mono"
                                                        key={index}
                                                    >
                                                        {tech}
                                                    </span>
                                                )
                                            )}
                                        </div>
                                    </div>
                                )
                            }
                        )}
                    </div>
                </section>
            </div>
        </>
    )
}

const IntroSection = styled.section`
    position: relative;
    z-index: 3;
    background: linear-gradient(
        0deg,
        var(--color-homepage-dark),
        var(--color-homepage-light)
    );
    transition: --color-homepage-light 350ms linear 0s,
        --color-homepage-dark 350ms linear 0s;
`

export async function getStaticProps(ctx) {
    const about = await axios.get("/api/about")

    return {
        props: {
            about: about || {},
        },
    }
}

Home.getLayout = (page: React.ReactNode) => <Main>{page}</Main>
